version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --coverage && yarn coveralls < coverage/lcov.info
workflows:
  tests:
    jobs:
      - test
